Hostname=CPE-Default
AllowRoot=1
Server=zabbix.switch-net.com
ServerActive=zabbix.switch-net.com
LogFile=/tmp/zabbix_agentd.log
LogFileSize=1
AllowKey=system.run[*]
StartAgents=1
Timeout=10
BufferSend=5
BufferSize=100

UserParameter=ping.delay[*],fping -c 4 -t 1000 $1 2>&1 | grep -oE "[0-9]+(\.[0-9]+)? avg" | cut -d" " -f1
UserParameter=ping.loss[*],fping -c 4 -t 1000 $1 2>&1 | grep -oE "[0-9]+% loss" | grep -oE "[0-9]+"
