Hostname=CPE-Default
AllowRoot=1
Server=zabbix.switch-net.com
ServerActive=zabbix.switch-net.com
LogFile=/tmp/zabbix_agentd.log
LogFileSize=1
AllowKey=system.run[*]
StartAgents=1
Timeout=10
BufferSend=5
BufferSize=100
